# Generated by Django 5.1.2 on 2024-10-19 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legallinkerapp', '0002_remove_advocate_email_remove_advocate_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advocate',
            old_name='user',
            new_name='advocate',
        ),
    ]
