# Generated by Django 5.1.2 on 2024-11-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legallinkerapp', '0010_remove_message_updated_at_chatroom_message_chat_room'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
