# Generated by Django 5.1.2 on 2024-11-02 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legallinkerapp', '0011_delete_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatRoom',
        ),
    ]
