# Generated by Django 5.1.2 on 2024-11-02 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legallinkerapp', '0013_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advocate',
            name='location',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
